name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # 设置 docker 镜像名
  IMAGE_NAME: jenkins

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: yaokun/${IMAGE_NAME}
          #imageName: yaokun/${IMAGE_NAME}
          #repository: yaokun/${IMAGE_NAME}
          tag: centos # 默认latest，可以针对平台，修改tag
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
